### ISSUE TITLE
No se puede instalar

### ISSUE THREAD

**Issue by mariani10** [hazzo/laravel-afip-wrapper#1]
hola viejo, me tira este error cuando lo quiero instalar vía composer en linux (centos) php7 y laravel 5.1

[InvalidArgumentException]                                                   
  Could not find package hazzo/LaravelAfipWrapper at any version for your min  
  imum-stability (stable). Check the package spelling or your minimum-stabili  
  ty                                                                           
          
tenés alguna idea? Saludoss

**Comment by hazzo** [comment]
Hola @mariani10.
Es que está en develop todavía. No hay un release estable.
Solo estoy conectandome con la asquerosa api de la AFIP. Quería hacer todos los métodos para crear facturas pero de momento no tuve tiempo.
Si pones en el composer.json a pelo la versión que figura en packagist debería tirar.

**Comment by mariani10** [comment]
Gracias, me imagine algo así por el msj, le tiraba que me instale con --dev y nada, con ignore-reqs tampoco, ya lo pude instalar, voy a empezar a jugar con el web service de afip, si logro algún metodo que quede copado lo aporto sin dramas. Saludos y gracias.

**Comment by hazzo** [comment]
Dale buenísimo. Creo que están extraídos todos los métodos para crear las facturas del XML pedorro de la AFIP.  No sé si están en ese release. Creo que ni lo subí a GitHub. Desp le echo un ojo y si los tengo por subir los subo.
